name: mm_scripting_util
channels:
- pytorch
- anaconda
- defaults
dependencies:
- python=3.6.*
- numpy
- h5py
- scipy=1.0.*
- scikit-learn=0.19.*
- six
- pytorch=0.4.*
- pytest
- corner
- shutil
- sys
- os
- platform
- getpass
- traceback
- matplotlib
- inspect
- enum
- collections
- scipy.stats
- tabulate 
- glob
- json
- argparse
- pip
- pip:
  - uproot
  - scikit-hep
  - madminer